from django.core.management.base import BaseCommand
from catalog.models import Category, Product, Review
from django.utils.text import slugify
import random

class Command(BaseCommand):
    help = 'Populate the database with sample categories, products, and reviews.'

    def handle(self, *args, **kwargs):
        categories = ['Electronics', 'Clothing', 'Home & Garden', 'Sports', 'Books']
        for name in categories:
            Category.objects.get_or_create(name=name, slug=slugify(name))

        sample_products = [
            ('Smartphone X', 'Electronics'),
            ('Laptop Pro', 'Electronics'),
            ('Cotton T-Shirt', 'Clothing'),
            ('Yoga Mat', 'Sports'),
            ('Garden Shovel', 'Home & Garden'),
            ('Cooking Pan Set', 'Home & Garden'),
            ('Running Shoes', 'Sports'),
            ('Sci-Fi Novel', 'Books'),
            ('History Book', 'Books'),
            ('Winter Jacket', 'Clothing'),
        ]

        for name, category_name in sample_products:
            category = Category.objects.get(name=category_name)
            product, _ = Product.objects.get_or_create(
                name=name,
                category=category,
                slug=slugify(name),
                description=f"{name} is a high-quality product in {category.name}",
                price=random.randint(1000, 50000) / 100,
                stock=random.randint(10, 100),
                image="products/sample.jpg"
            )

            for _ in range(random.randint(2, 5)):
                Review.objects.create(
                    product=product,
                    title=f"{random.choice(['Great', 'Average', 'Excellent', 'Bad'])} Product",
                    content="This is an autogenerated review.",
                    rating=random.randint(1, 5),
                    helpful_votes=random.randint(0, 10),
                    verified=random.choice([True, False])
                )

        self.stdout.write(self.style.SUCCESS('Sample data populated successfully.'))
